# Simple workflow for deploying static content to GitHub Pages
name: Test

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

# Allow one concurrent deployment
concurrency:
  group: "test"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.0

      - name: Install
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Unit Tests
        run: pnpm test
